package io.github.hsummerhays.atlas.agent;

import io.github.hsummerhays.atlas.service.ClaudeService;
import io.github.hsummerhays.atlas.service.GitHubIntegrationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
public class TestGenerationAgent implements AIAgent {

    private static final Logger log = LoggerFactory.getLogger(TestGenerationAgent.class);

    private static final String SYSTEM_PROMPT = """
            You are a senior Java engineer writing JUnit 5 tests for a Spring Boot shipping middleware.
            Generate a complete test class named exactly `AgentGeneratedTest` in package
            io.github.hsummerhays.atlas.generated, covering the task described by the user.
            Return ONLY the raw Java source code, no markdown code fences and no commentary.
            """;

    private static final String TEST_FILE_PATH =
            "src/test/java/io/github/hsummerhays/atlas/generated/AgentGeneratedTest.java";

    private final GitHubIntegrationService githubService;
    private final ClaudeService claudeService;

    public TestGenerationAgent(GitHubIntegrationService githubService, ClaudeService claudeService) {
        this.githubService = githubService;
        this.claudeService = claudeService;
    }

    @Override
    public AgentResult run(AgentRequest request) {
        log.info("TestGenerationAgent generating tests via Claude...");

        String taskDescription = request.inputData() != null && !request.inputData().isBlank()
                ? request.inputData()
                : "Generate JUnit 5 tests for ShipmentService";

        String testCode = claudeService.analyze(SYSTEM_PROMPT, taskDescription);

        String branchName = "feature/agent-generated-tests";
        String mainSha = githubService.getMainBranchSha();
        boolean branchCreated = githubService.createBranch(branchName, mainSha);

        if (!branchCreated) {
            return new AgentResult("TestGenerationAgent", false, "Failed to create branch: " + branchName, Map.of());
        }

        boolean pushed = githubService.pushFileToGitHub(
                branchName, TEST_FILE_PATH, testCode, "AI: add generated tests");

        if (!pushed) {
            return new AgentResult("TestGenerationAgent", false, "Failed to push test file to GitHub", Map.of());
        }

        String prBody = String.format("""
                ## AI-Generated Unit Tests
                This Pull Request was generated by **TestGenerationAgent** from the request:
                > %s

                ### Code modifications:
                - Created/updated `%s`.

                *AI Governance: HITL review required before merging.*
                """, taskDescription, TEST_FILE_PATH);

        String prUrl = githubService.createPullRequest(
                "AI Test Generation: " + taskDescription,
                branchName,
                "main",
                prBody,
                List.of(getRequiredApprovalLevel().name().toLowerCase())
        );

        String outputSummary = String.format("Successfully generated tests!\nPR URL: %s", prUrl);

        return new AgentResult(
                "TestGenerationAgent",
                true,
                outputSummary,
                Map.of("prUrl", prUrl, "generatedFilePath", TEST_FILE_PATH)
        );
    }

    @Override
    public ApprovalLevel getRequiredApprovalLevel() {
        return ApprovalLevel.TESTS;
    }
}
