package com.inxpress.middleware.agent;

import com.inxpress.middleware.service.GitHubIntegrationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Map;

@Component
public class CarrierAdapterAgent implements AIAgent {

    private static final Logger log = LoggerFactory.getLogger(CarrierAdapterAgent.class);

    private final GitHubIntegrationService githubService;

    public CarrierAdapterAgent(GitHubIntegrationService githubService) {
        this.githubService = githubService;
    }

    @Override
    public AgentResult run(AgentRequest request) {
        log.info("CarrierAdapterAgent executing USPS Carrier Adapter scaffolding...");

        String branchName = "feature/agent-usps-adapter-scaffold";

        // 1. Get real main branch SHA and create feature branch
        String mainSha = githubService.getMainBranchSha();
        boolean branchCreated = githubService.createBranch(branchName, mainSha);
        if (!branchCreated) {
            return new AgentResult("CarrierAdapterAgent", false, "Failed to create branch: " + branchName, Map.of());
        }

        // 2. Update Carrier.java enum — read from local disk, push modified version to GitHub
        String carrierEnumPath = "src/main/java/com/inxpress/middleware/domain/model/Carrier.java";
        try {
            String content = Files.readString(Paths.get(carrierEnumPath));
            if (!content.contains("USPS")) {
                String updatedContent = content.replace("DHL", "DHL,\n    USPS");
                boolean pushed = githubService.pushFileToGitHub(
                        branchName, carrierEnumPath, updatedContent, "AI: register USPS enum value in Carrier.java");
                if (!pushed) {
                    return new AgentResult("CarrierAdapterAgent", false, "Failed to push updated Carrier enum", Map.of());
                }
                log.info("Pushed updated Carrier enum with USPS to branch {}", branchName);
            }
        } catch (Exception e) {
            log.error("Failed to read/update Carrier enum", e);
            return new AgentResult("CarrierAdapterAgent", false, "Failed to update Carrier enum: " + e.getMessage(), Map.of());
        }

        // 3. Push USPS adapter source files to branch
        String adapterBase = "src/main/java/com/inxpress/middleware/adapter/usps";
        String testBase = "src/test/java/com/inxpress/middleware/adapter/usps";

        if (!githubService.pushFileToGitHub(branchName, adapterBase + "/UspsProperties.java",
                getUspsPropertiesTemplate(), "AI: scaffold UspsProperties.java")) {
            return new AgentResult("CarrierAdapterAgent", false, "Failed to push UspsProperties", Map.of());
        }
        if (!githubService.pushFileToGitHub(branchName, adapterBase + "/UspsTokenService.java",
                getUspsTokenServiceTemplate(), "AI: scaffold UspsTokenService.java")) {
            return new AgentResult("CarrierAdapterAgent", false, "Failed to push UspsTokenService", Map.of());
        }
        if (!githubService.pushFileToGitHub(branchName, adapterBase + "/UspsAdapter.java",
                getUspsAdapterTemplate(), "AI: scaffold UspsAdapter.java")) {
            return new AgentResult("CarrierAdapterAgent", false, "Failed to push UspsAdapter", Map.of());
        }
        if (!githubService.pushFileToGitHub(branchName, testBase + "/UspsAdapterTest.java",
                getUspsAdapterTestTemplate(), "AI: scaffold UspsAdapterTest.java")) {
            return new AgentResult("CarrierAdapterAgent", false, "Failed to push UspsAdapterTest", Map.of());
        }

        // 4. Open Pull Request on GitHub
        String prBody = """
                ## AI-Generated USPS Carrier Adapter Scaffolding
                This Pull Request was generated by **CarrierAdapterAgent** to integrate USPS API support.

                ### Files Scaffolded:
                - `Carrier.java`: Registered `USPS` enum value.
                - `UspsProperties.java`: Configurations for client credentials and endpoints.
                - `UspsTokenService.java`: OAuth 2.0 Client credentials manager.
                - `UspsAdapter.java`: `CarrierAdapter` mapping and REST integration using Spring `RestClient`.
                - `UspsAdapterTest.java`: JUnit test cases.

                *AI Governance: Approved for Merge pending human verification.*
                """;
        String prUrl = githubService.createPullRequest(
                "AI Integration: USPS Carrier Adapter Scaffolding",
                branchName,
                "main",
                prBody
        );

        String outputSummary = String.format(
                "Successfully scaffolded USPS Carrier Adapter!\nPR URL: %s\nFiles generated:\n- UspsProperties.java\n- UspsTokenService.java\n- UspsAdapter.java\n- UspsAdapterTest.java",
                prUrl
        );

        return new AgentResult(
                "CarrierAdapterAgent",
                true,
                outputSummary,
                Map.of("prUrl", prUrl)
        );
    }

    private String getUspsPropertiesTemplate() {
        return """
                package com.inxpress.middleware.adapter.usps;

                import org.springframework.boot.context.properties.ConfigurationProperties;
                import org.springframework.context.annotation.Configuration;

                @Configuration
                @ConfigurationProperties(prefix = "carrier.usps")
                public class UspsProperties {
                    private String baseUrl = "https://api.usps.com";
                    private String clientId;
                    private String clientSecret;
                    private String accountNumber;

                    public String getBaseUrl() { return baseUrl; }
                    public void setBaseUrl(String baseUrl) { this.baseUrl = baseUrl; }
                    public String getClientId() { return clientId; }
                    public void setClientId(String clientId) { this.clientId = clientId; }
                    public String getClientSecret() { return clientSecret; }
                    public void setClientSecret(String clientSecret) { this.clientSecret = clientSecret; }
                    public String getAccountNumber() { return accountNumber; }
                    public void setAccountNumber(String accountNumber) { this.accountNumber = accountNumber; }
                }
                """;
    }

    private String getUspsTokenServiceTemplate() {
        return """
                package com.inxpress.middleware.adapter.usps;

                import org.springframework.stereotype.Service;
                import org.springframework.web.client.RestClient;

                @Service
                public class UspsTokenService {
                    private final UspsProperties properties;
                    private final RestClient restClient;

                    public UspsTokenService(UspsProperties properties) {
                        this.properties = properties;
                        this.restClient = RestClient.builder().baseUrl(properties.getBaseUrl()).build();
                    }

                    public String getAccessToken() {
                        // Simulated token retrieval for USPS
                        return "mock-usps-token";
                    }
                }
                """;
    }

    private String getUspsAdapterTemplate() {
        return """
                package com.inxpress.middleware.adapter.usps;

                import com.inxpress.middleware.adapter.CarrierAdapter;
                import com.inxpress.middleware.domain.model.Carrier;
                import com.inxpress.middleware.domain.model.Shipment;
                import com.inxpress.middleware.domain.model.ShipmentStatus;
                import org.springframework.stereotype.Component;
                import java.math.BigDecimal;
                import java.util.UUID;

                @Component
                public class UspsAdapter implements CarrierAdapter {

                    private final UspsProperties properties;
                    private final UspsTokenService tokenService;

                    public UspsAdapter(UspsProperties properties, UspsTokenService tokenService) {
                        this.properties = properties;
                        this.tokenService = tokenService;
                    }

                    @Override
                    public Carrier getCarrier() { return Carrier.USPS; }

                    @Override
                    public Shipment bookShipment(Shipment shipment) {
                        shipment.setTrackingNumber("94001" + UUID.randomUUID().toString().substring(0, 15).toUpperCase());
                        shipment.setStatus(ShipmentStatus.BOOKED);
                        shipment.setTotalCost(quoteRate(shipment));
                        return shipment;
                    }

                    @Override
                    public BigDecimal quoteRate(Shipment shipment) {
                        double totalWeight = shipment.getPackages().stream().mapToDouble(p -> p.weightInKg()).sum();
                        return BigDecimal.valueOf(8.20 + (totalWeight * 1.50));
                    }

                    @Override
                    public ShipmentStatus trackShipment(String trackingNumber) { return ShipmentStatus.IN_TRANSIT; }

                    @Override
                    public boolean cancelShipment(String trackingNumber) { return true; }
                }
                """;
    }

    private String getUspsAdapterTestTemplate() {
        return """
                package com.inxpress.middleware.adapter.usps;

                import com.inxpress.middleware.domain.model.Carrier;
                import org.junit.jupiter.api.Test;
                import org.springframework.beans.factory.annotation.Autowired;
                import org.springframework.boot.test.context.SpringBootTest;
                import org.springframework.test.context.ActiveProfiles;

                import static org.junit.jupiter.api.Assertions.*;

                @SpringBootTest
                @ActiveProfiles("test")
                public class UspsAdapterTest {

                    @Autowired
                    private UspsAdapter uspsAdapter;

                    @Test
                    public void testUspsCarrierCode() {
                        assertEquals(Carrier.USPS, uspsAdapter.getCarrier());
                    }
                }
                """;
    }

    @Override
    public ApprovalLevel getRequiredApprovalLevel() {
        return ApprovalLevel.ARCHITECTURE;
    }
}
