package com.inxpress.middleware.agent;

import com.inxpress.middleware.service.GitHubIntegrationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Map;

@Component
public class DocumentationAgent implements AIAgent {

    private static final Logger log = LoggerFactory.getLogger(DocumentationAgent.class);

    private final GitHubIntegrationService githubService;

    public DocumentationAgent(GitHubIntegrationService githubService) {
        this.githubService = githubService;
    }

    @Override
    public AgentResult run(AgentTask task) {
        log.info("DocumentationAgent executing OpenAPI and Architecture documentation workflow...");

        // Create target directory
        new File("docs").mkdirs();

        // 1. Generate OpenAPI Spec File
        File openApiFile = new File("docs/openapi.yaml");
        try (FileWriter writer = new FileWriter(openApiFile)) {
            writer.write(getOpenApiYamlTemplate());
            log.info("Wrote OpenAPI spec to: {}", openApiFile.getAbsolutePath());
        } catch (IOException e) {
            log.error("Failed to write openapi.yaml", e);
            return new AgentResult("DocumentationAgent", false, "Failed to write OpenAPI yaml: " + e.getMessage(), Map.of());
        }

        // 2. Generate Architecture Specifications File
        File archFile = new File("docs/architecture.md");
        try (FileWriter writer = new FileWriter(archFile)) {
            writer.write(getArchitectureMarkdownTemplate());
            log.info("Wrote Architecture spec to: {}", archFile.getAbsolutePath());
        } catch (IOException e) {
            log.error("Failed to write architecture.md", e);
            return new AgentResult("DocumentationAgent", false, "Failed to write architecture markdown: " + e.getMessage(), Map.of());
        }

        // 3. Open Pull Request on GitHub
        String branchName = "feature/agent-documentation-update";
        boolean branchCreated = githubService.createBranch(branchName, "main-sha-placeholder");

        String prUrl = "https://github.com/mock-owner/mock-repo/pull/43";
        if (branchCreated) {
            String prBody = """
                    ## AI-Generated Architecture & API Specs
                    This Pull Request was generated by **DocumentationAgent** at 10 PM Dev Cycle.
                    
                    ### Documents created/updated:
                    - `docs/openapi.yaml`: OpenAPI 3.0 REST endpoint descriptions.
                    - `docs/architecture.md`: System layout, DB patterns, and Mermaid sequence diagrams.
                    
                    *AI Governance: Approved for Merge pending human verification.*
                    """;
            prUrl = githubService.createPullRequest(
                    "AI Documentation: OpenAPI and Architecture Diagrams Update",
                    branchName,
                    "main",
                    prBody
            );
        }

        String outputSummary = String.format(
                "Successfully generated documentation!\nPR URL: %s\nFiles written:\n- docs/openapi.yaml\n- docs/architecture.md",
                prUrl
        );

        return new AgentResult(
                "DocumentationAgent",
                true,
                outputSummary,
                Map.of(
                        "prUrl", prUrl,
                        "openApiFilePath", openApiFile.getAbsolutePath(),
                        "architectureFilePath", archFile.getAbsolutePath()
                )
        );
    }

    private String getOpenApiYamlTemplate() {
        return """
                openapi: 3.0.3
                info:
                  title: InXpress Shipping Middleware API
                  version: 1.0.0
                  description: Standardized shipping domain endpoint specifications.
                paths:
                  /api/v1/shipments:
                    post:
                      summary: Create shipment
                      requestBody:
                        required: true
                        content:
                          application/json:
                            schema:
                              type: object
                      responses:
                        '201':
                          description: Shipment created successfully
                  /api/v1/shipments/{id}/book:
                    post:
                      summary: Book shipment with Carrier
                      parameters:
                        - name: id
                          in: path
                          required: true
                          schema:
                            type: integer
                      responses:
                        '200':
                          description: Shipment booked successfully
                """;
    }

    private String getArchitectureMarkdownTemplate() {
        return """
                # InXpress Middleware Architecture
                
                System architecture design and structural layout.
                
                ## Sequence Diagram: Booking Flow
                
                ```mermaid
                sequenceDiagram
                    participant Client
                    participant Controller
                    participant Service
                    participant Registry
                    participant Adapter
                    participant Carrier
                
                    Client->>Controller: POST /api/v1/shipments/{id}/book
                    Controller->>Service: bookShipment(id)
                    Service->>Registry: getAdapter(carrier)
                    Registry-->>Service: Return Adapter
                    Service->>Adapter: bookShipment(shipment)
                    Adapter->>Carrier: POST (FedEx/UPS/DHL API)
                    Carrier-->>Adapter: Return tracking number
                    Adapter-->>Service: Return booked shipment
                    Service-->>Controller: Return Shipment
                    Controller-->>Client: HTTP 200 OK
                ```
                """;
    }
}
