package com.inxpress.middleware.agent;

import com.inxpress.middleware.service.ClaudeService;
import com.inxpress.middleware.service.GitHubIntegrationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
public class DocumentationAgent implements AIAgent {

    private static final Logger log = LoggerFactory.getLogger(DocumentationAgent.class);

    private static final String OPENAPI_SYSTEM_PROMPT = """
            You are a technical writer generating an OpenAPI 3.0 specification (YAML) for a Spring Boot
            shipping middleware. Cover the REST endpoints relevant to the task described by the user.
            Return ONLY raw YAML, no markdown code fences and no commentary.
            """;

    private static final String ARCHITECTURE_SYSTEM_PROMPT = """
            You are a technical writer documenting the architecture of a Spring Boot shipping middleware.
            Produce a concise Markdown document (including a Mermaid sequence diagram where useful)
            describing the relevant flow for the task described by the user.
            Return ONLY raw Markdown, no commentary outside the document.
            """;

    private final GitHubIntegrationService githubService;
    private final ClaudeService claudeService;

    public DocumentationAgent(GitHubIntegrationService githubService, ClaudeService claudeService) {
        this.githubService = githubService;
        this.claudeService = claudeService;
    }

    @Override
    public AgentResult run(AgentRequest request) {
        log.info("DocumentationAgent generating documentation via Claude...");

        String taskDescription = request.inputData() != null && !request.inputData().isBlank()
                ? request.inputData()
                : "Document the current InXpress shipment API and architecture";

        String openApiYaml = claudeService.analyze(OPENAPI_SYSTEM_PROMPT, taskDescription);
        String architectureMarkdown = claudeService.analyze(ARCHITECTURE_SYSTEM_PROMPT, taskDescription);

        String branchName = "feature/agent-documentation-update";
        String mainSha = githubService.getMainBranchSha();
        boolean branchCreated = githubService.createBranch(branchName, mainSha);

        if (!branchCreated) {
            return new AgentResult("DocumentationAgent", false, "Failed to create branch: " + branchName, Map.of());
        }

        boolean openApiPushed = githubService.pushFileToGitHub(
                branchName, "docs/openapi.yaml", openApiYaml, "AI: update OpenAPI spec");

        boolean archPushed = githubService.pushFileToGitHub(
                branchName, "docs/architecture.md", architectureMarkdown, "AI: update architecture documentation");

        if (!openApiPushed || !archPushed) {
            return new AgentResult("DocumentationAgent", false, "Failed to push documentation files to GitHub", Map.of());
        }

        String prBody = String.format("""
                ## AI-Generated Architecture & API Specs
                This Pull Request was generated by **DocumentationAgent** from the request:
                > %s

                ### Documents created/updated:
                - `docs/openapi.yaml`: OpenAPI 3.0 REST endpoint descriptions.
                - `docs/architecture.md`: System layout and sequence diagrams.

                *AI Governance: HITL review required before merging.*
                """, taskDescription);

        String prUrl = githubService.createPullRequest(
                "AI Documentation: OpenAPI and Architecture Update",
                branchName,
                "main",
                prBody,
                List.of(getRequiredApprovalLevel().name().toLowerCase())
        );

        String outputSummary = String.format(
                "Successfully generated documentation!\nPR URL: %s\nFiles written:\n- docs/openapi.yaml\n- docs/architecture.md",
                prUrl
        );

        return new AgentResult(
                "DocumentationAgent",
                true,
                outputSummary,
                Map.of("prUrl", prUrl)
        );
    }

    @Override
    public ApprovalLevel getRequiredApprovalLevel() {
        return ApprovalLevel.DOCUMENTATION;
    }
}
