package com.inxpress.middleware.agent;

import com.inxpress.middleware.service.GitHubIntegrationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.Map;

@Component
public class DocumentationAgent implements AIAgent {

    private static final Logger log = LoggerFactory.getLogger(DocumentationAgent.class);

    private final GitHubIntegrationService githubService;

    public DocumentationAgent(GitHubIntegrationService githubService) {
        this.githubService = githubService;
    }

    @Override
    public AgentResult run(AgentRequest request) {
        log.info("DocumentationAgent executing OpenAPI and Architecture documentation workflow...");

        // Get real main SHA and create branch
        String branchName = "feature/agent-documentation-update";
        String mainSha = githubService.getMainBranchSha();
        boolean branchCreated = githubService.createBranch(branchName, mainSha);

        if (!branchCreated) {
            return new AgentResult("DocumentationAgent", false, "Failed to create branch: " + branchName, Map.of());
        }

        boolean openApiPushed = githubService.pushFileToGitHub(
                branchName,
                "docs/openapi.yaml",
                getOpenApiYamlTemplate(),
                "AI: update OpenAPI spec"
        );

        boolean archPushed = githubService.pushFileToGitHub(
                branchName,
                "docs/architecture.md",
                getArchitectureMarkdownTemplate(),
                "AI: update architecture documentation"
        );

        if (!openApiPushed || !archPushed) {
            return new AgentResult("DocumentationAgent", false, "Failed to push documentation files to GitHub", Map.of());
        }

        String prBody = """
                ## AI-Generated Architecture & API Specs
                This Pull Request was generated by **DocumentationAgent** at 10 PM Dev Cycle.

                ### Documents created/updated:
                - `docs/openapi.yaml`: OpenAPI 3.0 REST endpoint descriptions.
                - `docs/architecture.md`: System layout, DB patterns, and Mermaid sequence diagrams.

                *AI Governance: Approved for Merge pending human verification.*
                """;
        String prUrl = githubService.createPullRequest(
                "AI Documentation: OpenAPI and Architecture Diagrams Update",
                branchName,
                "main",
                prBody
        );

        String outputSummary = String.format(
                "Successfully generated documentation!\nPR URL: %s\nFiles written:\n- docs/openapi.yaml\n- docs/architecture.md",
                prUrl
        );

        return new AgentResult(
                "DocumentationAgent",
                true,
                outputSummary,
                Map.of("prUrl", prUrl)
        );
    }

    private String getOpenApiYamlTemplate() {
        return """
                openapi: 3.0.3
                info:
                  title: InXpress Shipping Middleware API
                  version: 1.0.0
                  description: Standardized shipping domain endpoint specifications.
                paths:
                  /api/v1/shipments:
                    post:
                      summary: Create shipment
                      requestBody:
                        required: true
                        content:
                          application/json:
                            schema:
                              type: object
                      responses:
                        '201':
                          description: Shipment created successfully
                  /api/v1/shipments/{id}/book:
                    post:
                      summary: Book shipment with Carrier
                      parameters:
                        - name: id
                          in: path
                          required: true
                          schema:
                            type: integer
                      responses:
                        '200':
                          description: Shipment booked successfully
                """;
    }

    private String getArchitectureMarkdownTemplate() {
        return """
                # InXpress Middleware Architecture

                System architecture design and structural layout.

                ## Sequence Diagram: Booking Flow

                ```mermaid
                sequenceDiagram
                    participant Client
                    participant Controller
                    participant Service
                    participant Registry
                    participant Adapter
                    participant Carrier

                    Client->>Controller: POST /api/v1/shipments/{id}/book
                    Controller->>Service: bookShipment(id)
                    Service->>Registry: getAdapter(carrier)
                    Registry-->>Service: Return Adapter
                    Service->>Adapter: bookShipment(shipment)
                    Adapter->>Carrier: POST (FedEx/UPS/DHL API)
                    Carrier-->>Adapter: Return tracking number
                    Adapter-->>Service: Return booked shipment
                    Service-->>Controller: Return Shipment
                    Controller-->>Client: HTTP 200 OK
                ```
                """;
    }

    @Override
    public ApprovalLevel getRequiredApprovalLevel() {
        return ApprovalLevel.DOCUMENTATION;
    }
}
