package com.inxpress.middleware.agent;

import com.inxpress.middleware.service.ClaudeService;
import com.inxpress.middleware.service.GitHubIntegrationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.Map;

@Component
public class PullRequestAgent implements AIAgent {

    private static final Logger log = LoggerFactory.getLogger(PullRequestAgent.class);

    private final GitHubIntegrationService githubService;
    private final ClaudeService claudeService;

    public PullRequestAgent(GitHubIntegrationService githubService, ClaudeService claudeService) {
        this.githubService = githubService;
        this.claudeService = claudeService;
    }

    @Override
    public AgentResult run(AgentRequest request) {
        log.info("PullRequestAgent executing code promotion workflow...");

        String taskDescription = request.inputData() != null ? request.inputData() : "Add a new feature";
        String branchName = "feature/agent-" + taskDescription.toLowerCase()
                .replaceAll("[^a-z0-9]+", "-")
                .replaceAll("^-|-$", "")
                .substring(0, Math.min(40, taskDescription.length()));

        String prUrl;

        try {
            // Step 1: Get main branch SHA and create feature branch
            log.info("[1/4] Fetching main branch SHA...");
            String mainSha = githubService.getMainBranchSha();

            log.info("[2/4] Creating branch: {}", branchName);
            githubService.createBranch(branchName, mainSha);

            // Step 3: Generate implementation via Claude
            log.info("[3/4] Generating implementation with Claude...");
            String systemPrompt = """
                    You are a senior Java Spring Boot engineer.
                    Generate a concise, production-quality Java implementation for the requested task.
                    Return only the Java code without markdown code fences.
                    """;
            String generatedCode = claudeService.analyze(systemPrompt, taskDescription);

            String filePath = "src/main/java/com/inxpress/middleware/generated/AgentGeneratedCode.java";
            githubService.pushFileToGitHub(branchName, filePath, generatedCode, "AI: " + taskDescription);

            // Step 4: Open Pull Request
            log.info("[4/4] Opening Pull Request on GitHub...");
            String prBody = String.format("""
                    ## AI-Generated Pull Request
                    This Pull Request was generated by **PullRequestAgent**.

                    ### Task:
                    %s

                    ### Actions:
                    - Created branch `%s` from main
                    - Generated implementation via Claude Opus
                    - Pushed implementation to branch

                    *AI Governance: HITL review required before merging.*
                    """, taskDescription, branchName);

            prUrl = githubService.createPullRequest(
                    "AI: " + taskDescription,
                    branchName,
                    "main",
                    prBody
            );

        } catch (Exception e) {
            log.error("PullRequestAgent workflow failed", e);
            return new AgentResult(
                    "PullRequestAgent",
                    false,
                    "Workflow failed: " + e.getMessage(),
                    Map.of()
            );
        }

        return new AgentResult(
                "PullRequestAgent",
                true,
                "Workflow completed successfully!\nPR Opened: " + prUrl,
                Map.of("prUrl", prUrl, "targetBranch", branchName)
        );
    }
}
