package com.inxpress.middleware.agent;

import com.inxpress.middleware.service.GitHubIntegrationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Map;

@Component
public class TestGenerationAgent implements AIAgent {

    private static final Logger log = LoggerFactory.getLogger(TestGenerationAgent.class);

    private final GitHubIntegrationService githubService;

    public TestGenerationAgent(GitHubIntegrationService githubService) {
        this.githubService = githubService;
    }

    @Override
    public AgentResult run(AgentTask task) {
        log.info("TestGenerationAgent executing JUnit test generation workflow...");

        // 1. Generate JUnit Test Code File
        String testCode = getGeneratedTestTemplate();
        File testFile = new File("src/test/java/com/inxpress/middleware/service/ShipmentServiceGeneratedTest.java");
        
        // Ensure parent directories exist
        testFile.getParentFile().mkdirs();

        try (FileWriter writer = new FileWriter(testFile)) {
            writer.write(testCode);
            log.info("Successfully wrote generated tests to: {}", testFile.getAbsolutePath());
        } catch (IOException e) {
            log.error("Failed to write generated tests to file system", e);
            return new AgentResult(
                    "TestGenerationAgent",
                    false,
                    "Failed to write JUnit test file: " + e.getMessage(),
                    Map.of()
            );
        }

        // 2. Simulate Coverage Analysis
        String coverageReport = """
                =======================================================
                JACOCO COVERAGE REPORT (SIMULATED FOR GENERATED CODE)
                =======================================================
                Class: com.inxpress.middleware.service.ShipmentService
                Branch Coverage: 92.5%
                Line Coverage: 95.0%
                Status: PASSED (Threshold: 85%)
                =======================================================
                """;

        // 3. Open Pull Request on GitHub
        String branchName = "feature/agent-shipment-service-tests";
        boolean branchCreated = githubService.createBranch(branchName, "main-sha-placeholder");
        
        String prUrl = "https://github.com/mock-owner/mock-repo/pull/42";
        if (branchCreated) {
            String prBody = """
                    ## AI-Generated Unit & Integration Tests
                    This Pull Request was generated by **TestGenerationAgent** at 10 PM Dev Cycle.
                    
                    ### Code modifications:
                    - Created `ShipmentServiceGeneratedTest.java` targeting `ShipmentService`.
                    
                    ### Coverage Metrics:
                    - **Line Coverage**: 95.0%
                    - **Branch Coverage**: 92.5%
                    
                    *AI Governance: Approved for Merge pending human verification.*
                    """;
            prUrl = githubService.createPullRequest(
                    "AI Test Generation: ShipmentService Coverage Update",
                    branchName,
                    "main",
                    prBody
            );
        }

        String outputSummary = String.format(
                "Successfully generated tests!\nPR URL: %s\n\n%s",
                prUrl,
                coverageReport
        );

        return new AgentResult(
                "TestGenerationAgent",
                true,
                outputSummary,
                Map.of(
                        "prUrl", prUrl,
                        "generatedFilePath", testFile.getAbsolutePath(),
                        "coverageLineScore", 0.95
                )
        );
    }

    private String getGeneratedTestTemplate() {
        return """
                package com.inxpress.middleware.service;
                
                import com.inxpress.middleware.domain.model.Carrier;
                import com.inxpress.middleware.domain.model.Shipment;
                import com.inxpress.middleware.domain.model.ShipmentStatus;
                import com.inxpress.middleware.domain.repository.ShipmentRepository;
                import org.junit.jupiter.api.Test;
                import org.springframework.beans.factory.annotation.Autowired;
                import org.springframework.boot.test.context.SpringBootTest;
                import org.springframework.test.context.ActiveProfiles;
                
                import static org.junit.jupiter.api.Assertions.*;
                
                @SpringBootTest
                @ActiveProfiles("test")
                public class ShipmentServiceGeneratedTest {
                
                    @Autowired
                    private ShipmentService shipmentService;
                
                    @Autowired
                    private ShipmentRepository shipmentRepository;
                
                    @Test
                    public void testCreateShipment() {
                        Shipment shipment = new Shipment();
                        shipment.setCarrier(Carrier.FEDEX);
                        shipment.setServiceType("PRIORITY_OVERNIGHT");
                        
                        Shipment saved = shipmentService.createShipment(shipment);
                        assertNotNull(saved.getId());
                        assertEquals(ShipmentStatus.CREATED, saved.getStatus());
                    }
                }
                """;
    }
}
